// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxFFVTX_gyYzOX4KtfLVlFb55K8pIIpQ0',
    appId: '1:895131101601:web:97c7b7557469c5d0e143e0',
    messagingSenderId: '895131101601',
    projectId: 'finder-1-0-0',
    authDomain: 'finder-1-0-0.firebaseapp.com',
    storageBucket: 'finder-1-0-0.appspot.com',
    measurementId: 'G-K6GL4EN8X0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFQB-GYDvRa5HqFbAweCTJytz6j_tHB3k',
    appId: '1:895131101601:android:9454ecc6f5368b5be143e0',
    messagingSenderId: '895131101601',
    projectId: 'finder-1-0-0',
    storageBucket: 'finder-1-0-0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4C43bF15503c8GZyj-YfNUY4U59vToYg',
    appId: '1:895131101601:ios:1722e55cc071fffae143e0',
    messagingSenderId: '895131101601',
    projectId: 'finder-1-0-0',
    storageBucket: 'finder-1-0-0.appspot.com',
    iosBundleId: 'com.example.finder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4C43bF15503c8GZyj-YfNUY4U59vToYg',
    appId: '1:895131101601:ios:1722e55cc071fffae143e0',
    messagingSenderId: '895131101601',
    projectId: 'finder-1-0-0',
    storageBucket: 'finder-1-0-0.appspot.com',
    iosBundleId: 'com.example.finder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxFFVTX_gyYzOX4KtfLVlFb55K8pIIpQ0',
    appId: '1:895131101601:web:f1419ef34292c315e143e0',
    messagingSenderId: '895131101601',
    projectId: 'finder-1-0-0',
    authDomain: 'finder-1-0-0.firebaseapp.com',
    storageBucket: 'finder-1-0-0.appspot.com',
    measurementId: 'G-HS07EJWM3X',
  );
}
